// import '@/styles/globals.css'
// import '@/styles/sb-admin-2.module.css'
import '@/styles/globals2.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className='root-app'>
      <Head>
        <title>Hello2 App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="css/global2.css" />
      </Head>
      <Component {...pageProps} />
    </div>
  )
}
